version: "3.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Dhaka
    volumes:
      - ${config}/Duplicati/config:/config
      - ${groot}:/groot
      - ${rocket}:/rocket
      - ${mahi160}:/mahi160
      - /:/system
    ports:
      - 8200:8200
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - 8191:8191
    restart: unless-stopped

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"

      - "8088:80/tcp"
      - "3001:3000/tcp"
    environment:
      - TZ='Asia/Dhaka'
      - WEBPASSWORD=${pass}
    volumes:
      - ${config}/Adguardhome/work:/opt/adguardhome/work
      - ${config}/Adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "90:80/tcp"
  #   environment:
  #     TZ: 'Asia/Dhaka'
  #     WEBPASSWORD: ${pass}
  #   dns:
  #     - 127.0.0.1
  #     - 8.8.8.8
  #   volumes:
  #     - ${config}/Pihole/config:/etc/pihole
  #     - ${config}/Pihole/dnsmasq.d:/etc/dnsmasq.d
  #   restart: unless-stopped

  # homarr:
  #   container_name: homarr
  #   image: ghcr.io/ajnart/homarr:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ${config}/Homarr/config:/app/data/configs
  #     - ${config}/Homarr/icons:/app/public/icons
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - '7575:7575'
